### PR TITLE
Use stash count from 'git status' if available

### PR DESCRIPTION
**Pull request by Cyberbeni**
https://github.com/git/git/commit/dea96aae4d4821a7d516257daa6be4be893887cd

### CODE REVIEW

**Comment by Cyberbeni** [comment]
From the readme:

> Added a shell-only implementation. This avoids the startup cost of Python or Haskell.

If I understand this correctly then the shell-only implementation is better in both performance and also doesn't require any extra dependency, so the other two should be deleted.

**Comment by thomasrebele** [comment]
Thank you for the proposal (and sorry for the late reply). Somehow the proposed git command does not work as expected on my machine:

```
$ git stash list | wc -l | sed 's/^ *//'
2
$ git --no-optional-locks status --porcelain=v2 --branch --show-stash
# branch.oid d86d9eca8aa274ae8ca6891448e42a4c2266f8e8
# branch.head master
$ git --no-optional-locks status --porcelain=v2 --branch             
# branch.oid d86d9eca8aa274ae8ca6891448e42a4c2266f8e8
# branch.head master
$ git status --show-stash
On branch master
nothing to commit, working tree clean
Your stash currently has 2 entries
```

What git version are you using? Mine is 2.30.2. The --show-stash option is mentioned in the man page, however it seems to affect the non-porcelain output only.

> If I understand this correctly then the shell-only implementation is better in both performance and also doesn't require any extra dependency, so the other two should be deleted.

The Python and Haskell versions have disadvantages. I would just marking them as legacy or deprecated instead of removing them, though. Their source code takes less than 100kB of space, and compiling them is not required.

**Comment by Cyberbeni** [comment]
This change have been merged after the latest git release (2.34.1), so it hasn't been released yet. That's why there is a fallback to the previous method of getting the stash count.

**Comment by thomasrebele** [comment]
Now I understand the proposal. I had overlooked the fallback mechanism. Nice idea. Thank you for your contribution!

**Pull request merged**
